from typing import Literal

from srcFiles.bankPackage.bankAccount import BankAccount
import pytest

@pytest.mark.parametrize("testInput, expectedBalance",
                         [(BankAccount(1,1300), 1300),
                          (BankAccount(0,0), 0),
                          (BankAccount(1000,500), 500)      
                          ])
def test_getBalance(testInput, expectedBalance):
    assert testInput.getBalance() == expectedBalance
    
@pytest.mark.parametrize("testInput, expectedAccountID",
                         [(BankAccount(1,1300), 1),
                          (BankAccount(0,0), 0),
                          (BankAccount(1000,500), 1000)      
                          ])
def test_getAccountID(testInput, expectedAccountID):
    assert testInput.getAccountID() == expectedAccountID

#****AddMoney**** 
#positive testing
@pytest.mark.parametrize("testInput, addedMoney",
                         [(BankAccount(1,1300), 1000),
                          (BankAccount(0,0), 500),
                          (BankAccount(1000,500), 2000)      
                          ])
def test_addMoney(testInput, addedMoney):
    originalBalance = testInput.getBalance()
    testInput.addMoney(addedMoney)
    assert (originalBalance + addedMoney) == testInput.getBalance()
    
#negative testing
@pytest.mark.parametrize("testInput, addedMoney",
                         [(BankAccount(1,1300), -1301),
                          (BankAccount(0,0), -500),
                          (BankAccount(1000,500), -2000)      
                          ])
def test_Minus_addMoney(testInput, addedMoney):
    with pytest.raises(ValueError, match = "invalid amount. It must be > 0"):
        testInput.addMoney(addedMoney)


#****Withdraw**** 
#inrange testing*
@pytest.mark.parametrize("testInput, requestedMoney",
                         [(BankAccount(1,1300), 300),
                          (BankAccount(0,0), 0),
                          ])
def test_withDraw(testInput, requestedMoney):
    originalBalance = testInput.getBalance()
    testInput.withDraw(requestedMoney);
    assert testInput.getBalance() == (originalBalance - requestedMoney)
#boundary + 1
@pytest.mark.parametrize("testInput, requestedMoney",
                         [(BankAccount(1,1300), 1301),
                          (BankAccount(0,0), 1),
                          ])
def test_withDraw_boundary_plus_1(testInput, requestedMoney):
    with pytest.raises(ValueError, match = "invalid amount, it is > than the available balance"):
        testInput.withDraw(requestedMoney)
    
#boundary - 1
@pytest.mark.parametrize("testInput, requestedMoney",
                         [(BankAccount(1,1300), 1299),
                          (BankAccount(0,100), 99),
                          ])
def test_withDraw_boundary_minus_1(testInput, requestedMoney):
    originalBalance = testInput.getBalance()
    testInput.withDraw(requestedMoney);
    assert testInput.getBalance() == (originalBalance - requestedMoney)
#withdraw negative values
@pytest.mark.parametrize("testInput, requestedMoney",
                         [(BankAccount(1,1300), -1300),
                          (BankAccount(0,0), -0.1),
                          ])
def test_withDraw_negative_amount(testInput, requestedMoney):
    with pytest.raises(ValueError, match = "invalid amount, it is < 0€"):
        testInput.withDraw(requestedMoney)
        
#****TransferFundsTo**** 
@pytest.mark.parametrize("testInput, requestedMoney",
                         [(BankAccount(1,1300), 1300),
                          (BankAccount(0,0), 0),
                          (BankAccount(0,10000), 500),
                          ])
#nominal case
def test_transferFundsTo(testInput, requestedMoney):
    targetBbankAccount = BankAccount(10,0)
    testInput.transferFundsTo(targetBbankAccount, requestedMoney)
    assert targetBbankAccount.getBalance() == requestedMoney
#transfer negative funds
@pytest.mark.parametrize("testInput, requestedMoney",
                         [(BankAccount(1,1300), -1300),
                          (BankAccount(0,0), -1),
                          (BankAccount(0,10000), -10),
                          ])
def test_transferFundsTo_negative(testInput, requestedMoney):
    targetBbankAccount = BankAccount(10,0)
    with pytest.raises(ValueError, match = "invalid amount, it should be > 0€"):
        testInput.transferFundsTo(targetBbankAccount, requestedMoney)
'''
test cases generated by ChatGPT (GibtHub copilot), based on the code in srcFiles/bankPackage/bankAccount.py.
'''
@pytest.mark.parametrize(
    "account_id,balance",
    [
        (1, -100),
        (0, -1000),
        (0, -0.75),
    ],
)
def test_constructor_negative_balance_raises(account_id, balance):
    with pytest.raises(ValueError, match="invalid amount. It must be > 0"):
        BankAccount(account_id, balance)

@pytest.mark.parametrize(
    "accountId, balance",
    [
        (1, 0),
        (150, 15010000.75),
        (0, 1),
    ],
)
def test_setters_modify_state(accountId, balance):
    acc = BankAccount(0, 0)
    acc.setBalance(balance)
    acc.setAccountID(accountId)
    assert acc.getBalance() == balance
    assert acc.getAccountID() == accountId


def test_transfer_to_none_raises_typeerror():
    src = BankAccount(1, 100)
    with pytest.raises(TypeError, match="target bank account not defined"):
        src.transferFundsTo(None, 10)

#transfered funds > available balance
def test_transfer_funds_greater_than_balance_raises():
    src = BankAccount(1, 100)
    tgt = BankAccount(2, 0)
    with pytest.raises(ValueError, match="invalid amount, it is > than the available balance"):
        src.transferFundsTo(tgt, 200)


def test_withdraw_exact_balance_to_zero():
    acc = BankAccount(1, 100)
    acc.withDraw(100)
    assert acc.getBalance() == 0


def test_add_money_zero_no_change():
    acc = BankAccount(1, 50)
    acc.addMoney(0)
    assert acc.getBalance() == 50


