name: 02 - Auto Open Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --fill || echo "PR already exists or nothing to do"