name: 01 - Run Pytest
on: [workflow_dispatch]
jobs:
  pytestRegression:
    name: Run tests with pytest
    runs-on: ubuntu-latest

    steps:
      - name: Display event information  
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Display runner information
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Display repository information
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Run pytest
        run: |
          python -m pytest testFiles
  autoPR:
    name: Generate a new PR
    runs-on: ubuntu-latest

